/**
 * P.L.A.N.T.S. API
 * Provides functions to interact with P.L.A.N.T.S. systems
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Sensor } from '../model/sensor';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SensorService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * get all sensors
     * This can be done by 3rd party app
     * @param microbitId 
     * @param sensor 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSensors(microbitId: number, sensor?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Sensor>>;
    public getSensors(microbitId: number, sensor?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Sensor>>>;
    public getSensors(microbitId: number, sensor?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Sensor>>>;
    public getSensors(microbitId: number, sensor?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (microbitId === null || microbitId === undefined) {
            throw new Error('Required parameter microbitId was null or undefined when calling getSensors.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sensor !== undefined && sensor !== null) {
            queryParameters = queryParameters.set('sensor', <any>sensor);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Sensor>>(`${this.basePath}/plants/sensors/${encodeURIComponent(String(microbitId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update sensing time of a sensor of a microbit_it
     * This can be done by 3rd party app
     * @param microbitId 
     * @param sensorName 
     * @param sensingTime 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSensingTime(microbitId: number, sensorName: string, sensingTime: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateSensingTime(microbitId: number, sensorName: string, sensingTime: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateSensingTime(microbitId: number, sensorName: string, sensingTime: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateSensingTime(microbitId: number, sensorName: string, sensingTime: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (microbitId === null || microbitId === undefined) {
            throw new Error('Required parameter microbitId was null or undefined when calling updateSensingTime.');
        }

        if (sensorName === null || sensorName === undefined) {
            throw new Error('Required parameter sensorName was null or undefined when calling updateSensingTime.');
        }

        if (sensingTime === null || sensingTime === undefined) {
            throw new Error('Required parameter sensingTime was null or undefined when calling updateSensingTime.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sensingTime !== undefined && sensingTime !== null) {
            queryParameters = queryParameters.set('sensing_time', <any>sensingTime);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<any>(`${this.basePath}/plants/sensing/${encodeURIComponent(String(microbitId))}/${encodeURIComponent(String(sensorName))}`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
